pub mod redistribute_chars_to_make_all_str_eq_1897;
pub mod number_of_segments_in_string_434;
pub mod sentence_similarity_734;
pub mod percentage_of_letter_in_str_2278;
pub mod increasing_decreasing_string_1370;
pub mod count_binary_substrings_696;
pub mod count_vowel_substrings_of_a_string_2062;
pub mod check_if_number_has_equal_digit_count_and_digit_value_2283;
pub mod number_of_lines_to_write_str_806;
pub mod di_string_match_942;
pub mod remove_palindromic_subsequences_1332;
pub mod shortest_word_distance_243;
pub mod longest_nice_substring_1763;
pub mod occurrences_after_bigram_1078;

